-- RenameEnum
ALTER TYPE "Plan" RENAME VALUE 'HOBBYIST' TO 'FREE';
ALTER TYPE "Plan" RENAME VALUE 'BUSINESS' TO 'ENTERPRISE';
ALTER TYPE "Plan" RENAME VALUE 'BUSINESS_PLUS' TO 'ENTERPRISE_PLUS';

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "plan" SET DEFAULT 'FREE';
