// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "./src/load-env";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Non-null assertion: db.ts and seed.ts throw early if DATABASE_URL is unset
    url: process.env["DATABASE_URL"]!,
  },
});
